### ISSUE TITLE
にるぽ

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/showks-github-repository-operator#21]
Formからリソースを作成しようとしたところ、 `github-repository-operator-controller-manager-0` が死に続けるようになりました。

github-repository-operator-controller-manager-0のログは以下

```
Reconcile
setFinalizer
E0718 03:23:13.596966       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/pkg/gh/gh.go:67
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/pkg/controller/github_repository/github_repository_controller.go:122
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa38ed4]

goroutine 153 [running]:
github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1387b20, 0x20cdaf0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cloudnativedaysjp/showks-github-repository-operator/pkg/gh.(*GithubClient).GetRepository(0xc42000c7d0, 0xc42041ff80, 0x11, 0xc42041ff60, 0x11, 0xc42041babc, 0x3, 0x167edc0)
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/pkg/gh/gh.go:67 +0x84
github.com/cloudnativedaysjp/showks-github-repository-operator/pkg/controller/github_repository.(*ReconcileGitHub).Reconcile(0xc4201c2b70, 0xc42041baf9, 0x7, 0xc42041babc, 0x3, 0x20e2a60, 0x0, 0x0, 0x0)
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/pkg/controller/github_repository/github_repository_controller.go:122 +0x235
github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc420168c80, 0x0)
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x188
github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4200785c0)
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4200785c0, 0x3b9aca00, 0x0, 0x1, 0xc4204b2360)
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4200785c0, 0x3b9aca00, 0xc4204b2360)
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/cloudnativedaysjp/showks-github-repository-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x35b
```

作成したリソースのManifestは以下です

```
apiVersion: showks.cloudnativedays.jp/v1beta1
kind: GitHubRepository
metadata:
  creationTimestamp: "2019-07-18T03:19:54Z"
  finalizers:
  - finalizer.github.showks.cloudnativedays.jp
  generation: 2
  name: foo
  namespace: default
  resourceVersion: "8942020"
  selfLink: /apis/showks.cloudnativedays.jp/v1beta1/namespaces/default/githubrepositories/foo
  uid: e961c3b1-a90a-11e9-a25f-42010a9200f2
spec:
  collaborators:
  - name: bar
    permission: admin
  name: showks-canvas-foo
  org: cloudnativedaysjp
  template:
    name: ""
    org: ""
  webhooks:
  - active: true
    config:
      contentType: json
      url: https://example.com
    events:
    - push
```

たぶんtemplateが空欄なのが原因かな？

**Comment by takaishi** [comment]
`resp.Response.StatusCode` を見ようとしてニルポってる。errチェック入れないといけないな

https://github.com/cloudnativedaysjp/showks-github-repository-operator/blob/master/pkg/gh/gh.go#L67

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/showks-github-repository-operator/pull/22 で直した
